<?php

namespace AppBundle\Repository;

/**
 * CidadaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CidadaoRepository extends \Doctrine\ORM\EntityRepository
{
}
