# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    http_client:
      class: Zend\Http\Client
    dom_query:
      class: Zend\Dom\Query
    camara_deputado_service:
      class: AppBundle\Camara\Services\DeputadoService
      arguments: ['@http_client', '@dom_query', '@cache.app']
    camara_proposicao_service:
      class: AppBundle\Camara\Services\ProposicaoService
      arguments: ['@http_client', '@dom_query', '@cache.app']